### ISSUE TITLE
SET with options

### ISSUE THREAD

**Issue by kjersti** [chakrit/sider#12]
I would like to run the SET command with options (see http://redis.io/commands/set). 

I have tried using a custom call, but I get an error message back. 
Sider.ResponseException : Expecting a `SingleLine` reply while received error from Redis: ERR unknown command '$5'

Here is the code I am trying to run: 
var result = _redis.Custom("SET",
                writer =>
                {
                    writer.WriteArg(key);
                    writer.WriteArg(value);
                    writer.WriteArg("PX");
                    writer.WriteArg((int)_ttl.TotalMilliseconds);
                    writer.WriteArg("NX");
                },
                r => r.ReadOk());

Sample running the command in the shell:
localhost:0>SET key1 value1 PX 60000 NX 
OK
localhost:0>SET key1 value1 PX 60000 NX 
NULL
localhost:0>SET key1 value1 PX 60000 NX 
NULL

Am I doing something wrong in the Custom setup? Is it possible to include this command in the standard command set? 

Thanks!

**Comment by chakrit** [comment]
@kjersti hi! sorry for the super late reply. To fix your problem, you'll need to add a `WriteCmdStart` call to begin the multi-bulk send to redis (with proper number of arguments).

Something like `writer.WriteCmdStart("SET", 5)` the number `5` is the number of arguments (length of multi-bulk call)

**Comment by kjersti** [comment]
Thanks for the reply! :)
