### ISSUE TITLE
Running LUA scripts on the server?

### ISSUE THREAD

**Issue by kjersti** [chakrit/sider#13]
Is it possible to execute LUA scripts on the server using this client? 

I am specifically looking into implementing this pattern for using redis to store locks. See http://redis.io/topics/distlock.

In this pattern, the lock is created by issuing SET with options (see separate issue), and when releasing the lock, running the following LUA script.

if redis.call("get",KEYS[1]) == ARGV[1] then
    return redis.call("del",KEYS[1])
else
    return 0
end

Any tips on achieving this with the Sider client?

**Comment by chakrit** [comment]
@kjersti yes you can do this with the `.Custom` just like you did in the other issue.
