### ISSUE TITLE
Flag to know the current mode of client

### ISSUE THREAD

**Issue by cincauhangus** [chakrit/sider#16]
There is no methods/properties to know the current executor mode of the sider client.

**Comment by chakrit** [comment]
Available in 0.9.5 via `RedisClient.Mode` which returns the [`Mode` enum](https://github.com/chakrit/sider/blob/master/src/Sider/Mode.cs)

**Comment by chakrit** [comment]
@cincauhangus Also moved the executor init code into the `Reset()` as well so this *should* fix your "Cannot nest MULTI/EXEC" problem during resets.

Let me know if it still persists.
