### ISSUE TITLE
Dispose Threadwisepool

### ISSUE THREAD

**Issue by jcardeira** [chakrit/sider#20]
I'm trying to use this in a windows service. When I stop the service I need to stop all the threads otherwise the process will never die... For that I think a Dispose method would work.

Can it be done?

**Comment by chakrit** [comment]
@jcardeira sure, let me have a quick look.

**Comment by chakrit** [comment]
@jcardeira I've added `TrackedThreadwisePool` in [v0.10.0](https://www.nuget.org/packages/Sider/0.10.0) with a `Dipose()` for this. Let me know how it works out.

**Comment by jcardeira** [comment]
Thank you!!! I'll give it a try!
No dia 28 de Fev de 2016 06:04, "Chakrit Wichian" <notifications@github.com>
escreveu:
