### ISSUE TITLE
ZIP archive contains unsupported data structures.

### ISSUE THREAD

**Issue by NareshBanala** [chakrit/sider#23]
Getting "ZIP archive contains unsupported data structures." error when trying to install-package Sider 0.10.1 version.

@chakrit  Can you please resolve this as quickly as possible. We are trying to wrap up a release and we are depend on this.

**Comment by chakrit** [comment]
@NareshBanala that's a weird one. I'm checking.

**Comment by chakrit** [comment]
@NareshBanala I've tested with a fresh console project and things seems to be ok.

![2016-07-06 at 11 35 am](https://cloud.githubusercontent.com/assets/45545/16607685/4b2b9c80-436e-11e6-80dd-31ea9a7f06a4.png)

What's your current environment? (VS version, .NET version etc.)

**Comment by chakrit** [comment]
Also feel free to pop into [![Join the chat at https://gitter.im/chakrit/sider](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/chakrit/sider?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

Will be concentrating on my day job but I'll be online and I'll try to help if I have a spare moment.

**Comment by NareshBanala** [comment]
![packagemanagererror](https://cloud.githubusercontent.com/assets/6283722/16607794/e7f117a2-430a-11e6-86d7-73ec4792e5d6.png)
<img width="1075" alt="screen shot 2016-07-05 at 11 44 17 pm" src="https://cloud.githubusercontent.com/assets/6283722/16607797/efbd6ada-430a-11e6-8e34-35477c636b3d.png">
<img width="746" alt="screen shot 2016-07-05 at 11 41 49 pm" src="https://cloud.githubusercontent.com/assets/6283722/16607796/efbc6cc0-430a-11e6-860f-78a0f7a3cced.png">

**Comment by NareshBanala** [comment]
@chakrit  I had to delete all my nugget packages cache and install

**Comment by chakrit** [comment]
@NareshBanala version 0.10.2 is the same code but built using latest NuGet.exe on windows. I tested and the warning has disappeared. Let me know if this fixes your problem.

**Comment by chakrit** [comment]
https://www.nuget.org/packages/Sider/0.10.2.22156

**Comment by NareshBanala** [comment]
@chakrit , it is working now.
